# Generated by Django 4.0.3 on 2022-03-29 04:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=601)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/blog/')),
                ('description', models.TextField(blank=True, max_length=600)),
                ('text1', models.TextField(blank=True, max_length=1000)),
                ('text2', models.TextField(blank=True, max_length=1000)),
                ('text3', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='RichBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/blog/')),
                ('title', models.TextField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Editor',
                'verbose_name_plural': 'Blog Editor',
            },
        ),
        migrations.CreateModel(
            name='RichHomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rich_home_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Richhomeblogs', to='blog.richblog')),
            ],
            options={
                'verbose_name': 'Rich Home Blog',
                'verbose_name_plural': 'Rich Home Blog',
            },
        ),
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blogs', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Home Blog',
                'verbose_name_plural': 'Home Blog',
            },
        ),
    ]
