# Generated by Django 4.0.3 on 2022-03-29 04:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_richblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
