# Generated by Django 4.0.3 on 2022-03-29 17:39

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Section',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=401)),
                ('title_en', models.TextField(max_length=401, null=True)),
                ('title_ru', models.TextField(max_length=401, null=True)),
                ('title_uz', models.TextField(max_length=401, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('description_en', models.TextField(max_length=1000, null=True)),
                ('description_ru', models.TextField(max_length=1000, null=True)),
                ('description_uz', models.TextField(max_length=1000, null=True)),
                ('button_title', models.CharField(max_length=300)),
                ('button_title_en', models.CharField(max_length=300, null=True)),
                ('button_title_ru', models.CharField(max_length=300, null=True)),
                ('button_title_uz', models.CharField(max_length=300, null=True)),
                ('button_link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Home About Section 2',
                'verbose_name_plural': 'Home About Section 2',
            },
        ),
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_logo', models.ImageField(upload_to='images/logo/')),
                ('dark_logo', models.ImageField(upload_to='images/logo/')),
            ],
            options={
                'verbose_name': 'Home Logo',
                'verbose_name_plural': 'Home Logo',
            },
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Bosh sarlavha')),
                ('title_en', models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha')),
                ('title_ru', models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha')),
                ('title_uz', models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha')),
                ('description', models.TextField(max_length=500, verbose_name='Malumot')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='Malumot')),
                ('description_ru', models.TextField(max_length=500, null=True, verbose_name='Malumot')),
                ('description_uz', models.TextField(max_length=500, null=True, verbose_name='Malumot')),
                ('button1', models.CharField(max_length=100, verbose_name='Knopka 1')),
                ('button1_en', models.CharField(max_length=100, null=True, verbose_name='Knopka 1')),
                ('button1_ru', models.CharField(max_length=100, null=True, verbose_name='Knopka 1')),
                ('button1_uz', models.CharField(max_length=100, null=True, verbose_name='Knopka 1')),
                ('slug_button1', models.CharField(max_length=100, verbose_name='Knopka 1 Link')),
                ('button2', models.CharField(max_length=100, verbose_name='Knopka 2')),
                ('button2_en', models.CharField(max_length=100, null=True, verbose_name='Knopka 2')),
                ('button2_ru', models.CharField(max_length=100, null=True, verbose_name='Knopka 2')),
                ('button2_uz', models.CharField(max_length=100, null=True, verbose_name='Knopka 2')),
                ('slug_button2', models.CharField(max_length=100, verbose_name='Knopka 2 Link')),
            ],
            options={
                'verbose_name': 'Home Title',
                'verbose_name_plural': 'Home Title',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('title_en', ckeditor.fields.RichTextField(null=True)),
                ('title_ru', ckeditor.fields.RichTextField(null=True)),
                ('title_uz', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('link', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='SendNumberSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('title_en', models.TextField(max_length=500, null=True)),
                ('title_ru', models.TextField(max_length=500, null=True)),
                ('title_uz', models.TextField(max_length=500, null=True)),
                ('description', models.TextField(max_length=500)),
                ('description_en', models.TextField(max_length=500, null=True)),
                ('description_ru', models.TextField(max_length=500, null=True)),
                ('description_uz', models.TextField(max_length=500, null=True)),
                ('button_title', models.TextField(max_length=200)),
                ('button_title_en', models.TextField(max_length=200, null=True)),
                ('button_title_ru', models.TextField(max_length=200, null=True)),
                ('button_title_uz', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Send Number Section',
                'verbose_name_plural': 'Send Number Section',
            },
        ),
    ]
