# Generated by Django 4.0.3 on 2022-03-28 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Section',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=401)),
                ('description', models.TextField(max_length=1000)),
                ('button_title', models.CharField(max_length=300)),
                ('button_link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Home About Section 2',
                'verbose_name_plural': 'Home About Section 2',
            },
        ),
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_logo', models.ImageField(upload_to='images/logo/')),
                ('dark_logo', models.ImageField(upload_to='images/logo/')),
            ],
            options={
                'verbose_name': 'Home Logo',
                'verbose_name_plural': 'Home Logo',
            },
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Bosh sarlavha')),
                ('description', models.TextField(max_length=500, verbose_name='Malumot')),
                ('button1', models.CharField(max_length=100, verbose_name='Knopka 1')),
                ('slug_button1', models.CharField(max_length=100, verbose_name='Knopka 1 Link')),
                ('button2', models.CharField(max_length=100, verbose_name='Knopka 2')),
                ('slug_button2', models.CharField(max_length=100, verbose_name='Knopka 2 Link')),
            ],
            options={
                'verbose_name': 'Home Title',
                'verbose_name_plural': 'Home Title',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='SendNumberSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('button_title', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Send Number Section',
                'verbose_name_plural': 'Send Number Section',
            },
        ),
    ]
