# Generated by Django 4.0.3 on 2022-03-28 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
