# Generated by Django 4.0.3 on 2022-03-30 05:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_portfolio_content_alter_portfolio_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='nima'),
            preserve_default=False,
        ),
    ]
