# Generated by Django 4.0.3 on 2022-03-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaboutsection',
            name='description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='description_uz',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='title_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='title_ru',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='title_uz',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button1_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 1'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button1_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 1'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button1_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 1'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button2_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 2'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button2_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 2'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='button2_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Knopka 2'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='description_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='title_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='title_ru',
            field=models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha'),
        ),
        migrations.AddField(
            model_name='hometitle',
            name='title_uz',
            field=models.TextField(max_length=200, null=True, verbose_name='Bosh sarlavha'),
        ),
    ]
