# Generated by Django 4.0.3 on 2022-03-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_portfolio_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
    ]
