# Generated by Django 4.0.3 on 2022-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_portfolio_pdf_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pdf',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description1',
            field=models.TextField(default='njds', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description2',
            field=models.TextField(default='xcmk', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='dsfk', unique=True),
            preserve_default=False,
        ),
    ]
