# Generated by Django 4.0.3 on 2022-03-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_portfolio_content_remove_portfolio_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description1_en',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description1_ru',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description1_uz',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description2_en',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description2_ru',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description2_uz',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
