# Generated by Django 4.0.3 on 2022-03-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_portfolio_description1_en_portfolio_description1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='budget',
            field=models.CharField(default='elmax', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='clent',
            field=models.CharField(default='nimadur', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(default='sxklm', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='work_finished',
            field=models.CharField(default='dcxkm,', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='work_taken',
            field=models.CharField(default='xckm', max_length=300),
            preserve_default=False,
        ),
    ]
