# Generated by Django 4.0.3 on 2022-03-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_portfolio_budget_portfolio_clent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='clent',
            new_name='client',
        ),
    ]
