# Generated by Django 4.0.3 on 2022-03-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_clent_portfolio_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='service_type_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_type_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_type_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
