# Generated by Django 4.0.3 on 2022-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footerdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerdata',
            options={'verbose_name': 'Footer Logo and About', 'verbose_name_plural': 'Footer Logo And About'},
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='instagram',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='linkedin',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='footerdata',
            name='telegram',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
