# Generated by Django 4.0.3 on 2022-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_footerdata_options_alter_footerdata_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenuMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(choices=[('/', 'Home'), ('/portfolio/', 'Portfolio'), ('/blog/', 'Blog'), ('/about/', 'About'), ('/contact/', 'Contact')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FooterServiceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Footer Service Meta',
                'verbose_name_plural': 'Footer Service Meta',
            },
        ),
    ]
