# Generated by Django 4.0.3 on 2022-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_footermenumeta_footerservicemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenumeta',
            name='link',
            field=models.CharField(choices=[('index', 'Home'), ('portfolio', 'Portfolio'), ('/blog/', 'Blog'), ('/about/', 'About'), ('/contact/', 'Contact')], max_length=300),
        ),
    ]
