# Generated by Django 4.0.3 on 2022-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_footermenumeta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerdata',
            name='description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='footerdata',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='footerdata',
            name='description_uz',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='footermenumeta',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='footermenumeta',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='footermenumeta',
            name='title_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='footerservicemeta',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerservicemeta',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footerservicemeta',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
