# Generated by Django 4.0.3 on 2022-03-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_footerdata_description_en_footerdata_description_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterData',
        ),
        migrations.DeleteModel(
            name='FooterMenuMeta',
        ),
        migrations.DeleteModel(
            name='FooterServiceMeta',
        ),
    ]
