# Generated by Django 4.0.3 on 2022-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_logo', models.ImageField(upload_to='images/white_logo/')),
                ('description', models.TextField(max_length=1000)),
                ('description_en', models.TextField(max_length=1000, null=True)),
                ('description_ru', models.TextField(max_length=1000, null=True)),
                ('description_uz', models.TextField(max_length=1000, null=True)),
                ('telegram', models.CharField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('linkedin', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Footer Logo and About',
                'verbose_name_plural': 'Footer Logo And About',
            },
        ),
        migrations.CreateModel(
            name='FooterMenuMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_uz', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(choices=[('index', 'Home'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('about', 'About'), ('contact', 'Contact')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FooterServiceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('title_uz', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Footer Service Meta',
                'verbose_name_plural': 'Footer Service Meta',
            },
        ),
    ]
