# Generated by Django 4.0.3 on 2022-03-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenumeta',
            options={'verbose_name': 'Footer Menu Meta', 'verbose_name_plural': 'Footer Menu Meta'},
        ),
    ]
